name: hello-world

on: push

jobs:

  build:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Check Node.js version
        run: node --version

      - name: say-hello 
        run: make say-hello
